from display import dis as dis
import time

def setup():
    dis.clear()
    dis.text("CUANTAS CANICAS",1)
    dis.text("QUIERE?",2)
    time.sleep(1)
    dis.text("1 -UNA CANICA",1)
    dis.text("2 -DOS CANICAS",2)
    time.sleep(1)
    dis.text("3 -TRES CANICAS",1)
    dis.text("4 -SALIR",2)
    time.sleep(1)
    dis.clear()
def setup_2():
    dis.clear()
    dis.text("CUANTOS COLORES",1)
    dis.text("QUIERE?",2)
    time.sleep(1)
    dis.text("1 -UN COLOR",1)
    dis.text("2 -DOS COLORES",2)
    time.sleep(1)
    dis.text("3 -TRES COLORES",1)
    dis.text("4 -SALIR",2)
    time.sleep(1)
    dis.clear()
def setup_3():
    dis.clear()
    dis.text("QUE COLOR/ES",1)
    dis.text("QUIERE?",2)
    time.sleep(1)
    dis.text("1 -AZUL",1)
    dis.text("2 -AMARILLO",2)
    time.sleep(1)
    dis.text("3 -ROJO",1)
    dis.text("4 -SALIR",2)
    time.sleep(1)
    dis.clear()
def setup_4():
    dis.clear()
    dis.text("CUANTAS CAJAS",1)
    dis.text("QUIERE?",2)
    time.sleep(1)
    dis.text("1 -UNA CAJA",1)
    dis.text("2 -DOS CAJAS",2)
    time.sleep(1)
    dis.text("3 -TRES CAJAS",1)
    dis.text("4 -SALIR",2)
    time.sleep(1)
    dis.clear()